services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INIT_DATABASE: students
    ports:
      - 27017:27017
volumes:
  mongodb-data:
